name: hddm_tutorial_ian
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - astunparse=1.6.3
  - atom=0.5.1
  - attrs=19.3.0
  - backcall=0.2.0
  - bleach=3.1.5
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.15.0
  - ca-certificates=2020.6.24
  - cachetools=4.1.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cycler=0.10.0
  - cython=0.29.21
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - future=0.18.2
  - gast=0.3.3
  - git=2.23.0
  - glib=2.63.1
  - gmp=6.1.2
  - google-auth=1.14.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.9
  - importlib-metadata=1.6.1
  - ipykernel=5.3.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libsodium=1.0.16
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.10
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.5
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - packaging=20.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - protobuf=3.12.3
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pymc=2.3.8
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scipy=1.4.1
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=47.3.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.31.1
  - statsmodels=0.11.1
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wcwidth=0.2.4
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wget=1.20.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - hddm==0.7.5
    - joblib==0.16.0
    - kabuki==0.6.3
    - pandas==1.0.4
    - patsy==0.5.1
    - scikit-learn==0.23.1
    - sklearn==0.0
    - threadpoolctl==2.1.0


