import numpy as np
import pickle
import cddm_data_simulation as cd
import clba
import boundary_functions as bf
import os

tutorial_config = {
"ddm_tutorial":{
    "dgp": cd.ddm_flexbound, 
    "boundary": bf.constant,
    "boundary_multiplicative": True,
    "method_folder": "/users/afengler/data/kde/ddm_tutorial/",
    "method_folder_x7": "/media/data_cifs/afengler/data/kde/ddm_tutorial/",
    "method_folder_home": "/Users/afengler/OneDrive/project_nn_likelihoods/data/kde/ddm_tutorial/",
    "data_folder": "/users/afengler/data/kde/ddm_tutorial/train_test_data_ndt_20000/",
    "data_folder_x7": "/media/data_cifs/afengler/data/kde/ddm_tutorial/train_test_data_ndt_20000/",
    "data_folder_fcn": "/users/afengler/data/analytic/ddm_tutorial/fcn_train_test_data_2000",
    "data_folder_fcn_x7": "/media/data_cifs/afengler/data/analytic/ddm_tutorial/fcn_train_test_data_2000",
    #"custom_objects": {"huber_loss": tf.losses.huber_loss},
    #"fcn_custom_objects": {"heteroscedastic_loss": tf.losses.huber_loss},
    "output_folder": "/users/afengler/data/kde/ddm_tutorial/method_comparison/",
    "output_folder_x7": "/media/data_cifs/afengler/data/kde/ddm_tutorial/method_comparison/",
    "output_folder_home": "/Users/afengler/OneDrive/project_nn_likelihoods/data/kde/ddm_tutorial/method_comparison/",
    "model_folder": "/users/afengler/data/kde/ddm_tutorial/keras_models/",
    "model_folder_x7": "/media/data_cifs/afengler/data/kde/ddm_tutorial/keras_models/",
    "param_names": ['v', 'a', 'w', 'ndt'],
    "boundary_param_names": [],
    #"param_bounds_network": [[-2.0, 2.0], [0.5, 1.5], [0.3, 0.7], [0.0, 1.0]],  
    "param_bounds_network": [[-3.0, 3.0], [0.3, 2.5], [0.1, 0.9], [0.0, 2.0]],
    "param_bounds_sampler": [[-2.0, 2.0], [0.5, 2.0], [0.3, 0.7], [0.2, 1.8]],
    "param_bounds_cnn": [[-3.0, 3.0], [0.3, 2.5], [0.1, 0.9], [0.0, 2.0]],
    "boundary_param_bounds_network": [],
    "boundary_param_bounds_sampler": [],
    "boundary_param_bounds_cnn":[],
    "dgp_hyperparameters": [['s', 1.0], 
                            ['delta_t', 0.01], 
                            ['max_t', 20], 
                            ['n_samples', 20000], 
                            ['print_info', False],
                            ['boundary', bf.constant],
                            ['boundary_multiplicative', True]],
    },
"angle_tutorial":{
    "dgp": cd.ddm_flexbound,
    "boundary": bf.angle,
    "boundary_multiplicative": False,
    "method_folder": "/users/afengler/data/kde/angle_tutorial/",
    "method_folder_x7": "/media/data_cifs/afengler/data/kde/angle_tutorial/",
    "method_folder_home": "/Users/afengler/OneDrive/project_nn_likelihoods/data/kde/angle_tutorial/",
    "data_folder": "/users/afengler/data/kde/angle_tutorial/train_test_data_ndt_20000/",
    "data_folder_x7": "/media/data_cifs/afengler/data/kde/angle_tutorial/train_test_data_ndt_20000/",
    "output_folder": "/users/afengler/data/kde/angle_tutorial/method_comparison/",
    "output_folder_x7": "/media/data_cifs/afengler/data/kde/angle_tutorial/method_comparison/",
    "output_folder_home": "/Users/afengler/OneDrive/project_nn_likelihoods/data/kde/angle_tutorial/method_comparison/",
    "model_folder": "/users/afengler/data/kde/angle_tutorial/keras_models/",
    "model_folder_x7": "/media/data_cifs/afengler/data/kde/angle_tutorial/keras_models/",
    "param_names": ["v", "a", "w", "ndt"],
    "boundary_param_names": ["theta"],
    # "param_bounds_network": [[-1.5, 1.5], [0.6, 1.5], [0.3, 0.7], [0.0, 1.0]],
    "param_bounds_network": [[-2.0, 2.0], [0.3, 2], [0.2, 0.8], [0.0, 2.0]],
    "param_bounds_sampler": [[-2.0, 2.0], [0.5, 1.8], [0.3, 0.7], [0.2, 1.8]],
    "param_bounds_cnn": [[-2.5, 2.5], [0.2, 2.0], [0.1, 0.9], [0.0, 2.0]],
    #"boundary_param_bounds_network": [[0, (np.pi / 2 - .2)]],
    'boundary_param_bounds_network':[[0, (np.pi / 2 - .1)]],
    "boundary_param_bounds_sampler": [[0.2, np.pi / 2 - .5]],
    "boundary_param_bounds_cnn": [[0, (np.pi / 2 - .2)]],
    "dgp_hyperparameters": [['s', 1.0], 
                            ['delta_t', 0.01], 
                            ['max_t', 20], 
                            ['n_samples', 20000], 
                            ['print_info', False],
                            ['boundary', bf.angle],
                            ['boundary_multiplicative', False]],
    },
"weibull_cdf_tutorial":{
    "dgp": cd.ddm_flexbound,
    "boundary": bf.weibull_cdf,
    "boundary_multiplicative": True,
    "method_folder": "/users/afengler/data/kde/weibull_cdf_tutorial/",
    "method_folder_x7": "/media/data_cifs/afengler/data/kde/weibull_cdf_tutorial/",
    "method_folder_home": "/Users/afengler/OneDrive/project_nn_likelihoods/data/kde/weibull_cdf_tutorial/",
    "data_folder": "/users/afengler/data/kde/weibull_cdf_tutorial/train_test_data_ndt_20000/",
    "data_folder_x7": "/media/data_cifs/afengler/data/kde/weibull_cdf_tutorial/train_test_data_ndt_20000/",
    "output_folder": "/users/afengler/data/kde/weibull_cdf_tutorial/method_comparison/",
    "output_folder_x7": "/media/data_cifs/afengler/data/kde/weibull_cdf_tutorial/method_comparison/",
    "output_folder_home": "/Users/afengler/OneDrive/project_nn_likelihoods/data/kde/weibull_cdf_tutorial/method_comparison/",
    "model_folder": "/users/afengler/data/kde/weibull_cdf_tutorial/keras_models/",
    "model_folder_x7": "/media/data_cifs/afengler/data/kde/weibull_cdf_tutorial/keras_models/",
    "param_names": ["v", "a", "w", "ndt"],
    "boundary_param_names": ["alpha", "beta"],
    # "param_bounds_network": [[-1.5, 1.5], [0.6, 1.5], [0.3, 0.7], [0.0, 1.0]],
    "param_bounds_network": [[-3.0, 3.0], [0.3, 2], [0.2, 0.8], [0.0, 2.0]],
    "param_bounds_sampler": [[-2.0, 2.0], [0.5, 1.7], [0.3, 0.7], [0.2, 1.8]],
    "param_bounds_cnn": [[-3.0, 3.0], [0.3, 2.0], [0.1, 0.9], [0.0, 2.0]],
    #"boundary_param_bounds_network": [[0.5, 5.0], [0.5, 7.0]],
    "boundary_param_bounds_network": [[0.3, 5.0], [0.3, 7.0]],
    "boundary_param_bounds_sampler": [[1.0, 4.0], [1.0, 6.0]],
    "boundary_param_bounds_cnn": [[0.3, 5.0], [0.3, 7.0]],
    "dgp_hyperparameters": [['s', 1.0], 
                            ['delta_t', 0.01], 
                            ['max_t', 20], 
                            ['n_samples', 20000], 
                            ['print_info', False],
                            ['boundary', bf.weibull_cdf],
                            ['boundary_multiplicative', True]],
    },
}